# Numpy

- Numpy refers to a numeric-nonnegative integer function of python
- it can be used for data science
- to solve complicated mathematical task
- it is same like as lists
- but more efficient and fast than list i terms of executing tasks
- it is used for algebra and other important maths tasks

In [3]:
import numpy as np
a = np.array([3,4,4,5])
a

array([3, 4, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
len(a)

4

In [10]:
b = np.array([[2,3,4,5], [2,3,4,5], [2,3,4,5]])
b

array([[2, 3, 4, 5],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [11]:
c = np.zeros(2)
c

array([0., 0.])

In [12]:
c = np.zeros(4)
c

array([0., 0., 0., 0.])

In [16]:
d = np.empty(3)
d

array([9.76124901e-312, 0.00000000e+000, 1.24610994e-306])

In [20]:
d = np.ones(3)
d

array([1., 1., 1.])

In [21]:
d = np.empty(3)
d

array([1., 1., 1.])

In [22]:
d = np.arange(3)
d

array([0, 1, 2])

In [23]:
e = np.arange(8,20)
e

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
e = np.arange(8,20,3)
e

array([ 8, 11, 14, 17])

In [25]:
e = np.linspace(11,33,num=6)
e

array([11. , 15.4, 19.8, 24.2, 28.6, 33. ])

## 2D arrays

In [29]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3D arrays

In [49]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
a.ndim

3

In [51]:
b = np.arange(192).reshape(4,6,8)
b

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143]],

       [[144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 

In [52]:
b.ndim

3

In [1]:
import numpy as np

In [4]:
a = np.array([11, 44, 55, 7.9, 8.2])
a

array([11. , 44. , 55. ,  7.9,  8.2])

In [45]:
b.ndim

1

In [5]:
type(a)

numpy.ndarray

In [6]:
len(a)

5

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(5, 25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [23]:
np.arange(5,25,5)

array([ 5, 10, 15, 20])

In [27]:
a.sort()
a

array([ 7.9,  8.2, 11. , 44. , 55. ])

## 2D-arrays

In [40]:
b = np.array([[1,2,3,4,5,6] ,
               [4,5,6,7,8,9]])
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [41]:
b.ndim

2

In [48]:
b.shape

(3,)

## 3-D

In [53]:
c= np.arange(125).reshape(5,5,5)
c

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [55]:
c.ndim

3

In [67]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [73]:
b= np.array([11,2,3,44,33])
b

array([11,  2,  3, 44, 33])

In [69]:
type(a)

numpy.ndarray

In [70]:
type(b)

numpy.ndarray

In [74]:
c = np.concatenate((a, b))
c

array([ 1,  2,  3,  4,  5, 11,  2,  3, 44, 33])

In [75]:
type(c)

numpy.ndarray

In [76]:
#shape is the total number of elements in the paranthesis

c.shape

(10,)

In [77]:
c = a[np.newaxis, :]
c

array([[1, 2, 3, 4, 5]])

In [78]:
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [80]:
b.all()

True

In [81]:
b.any()

True

In [82]:
c.argmax()

4

In [83]:
c.argmin()

0

In [91]:
b.argpartition(0)

array([1, 0, 2, 3, 4], dtype=int64)

In [92]:
b.argsort()

array([1, 2, 0, 4, 3], dtype=int64)

In [2]:
b.sort()


NameError: name 'b' is not defined

In [102]:
b.base
b

array([11,  2,  3, 44, 33])

In [104]:
b.byteswap()

array([184549376,  33554432,  50331648, 738197504, 553648128])

ValueError: could not broadcast input array from shape (5,) into shape (5,1)

In [3]:
import numpy as np

In [6]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a.ndim

1

In [10]:
b= np.array([[6,7,8,9,0], [5,6,9,3,4]])
b


array([[6, 7, 8, 9, 0],
       [5, 6, 9, 3, 4]])

In [12]:
b.ndim

2

In [15]:
c= np.array([[[6,7,8,9,0], [5,6,9,3,4], [2,4,3,8,7]]])
c

array([[[6, 7, 8, 9, 0],
        [5, 6, 9, 3, 4],
        [2, 4, 3, 8, 7]]])

In [16]:
c.ndim

3

In [19]:
a.base
a

array([1, 2, 3, 4, 5])

In [28]:
np.choose(a,c)

ValueError: invalid entry in choice array